## **Creating Data Frame**

In [1]:
# using csv
import pandas as pd
df = pd.read_csv('sample_weather_data01.csv')
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [6]:
# using excel
df = pd.read_excel("sample_weather_data.xlsx", "Sheet1")
df

         day  temperature  windspeed  event
0 2017-01-01         32.0        6.0   Rain
1 2017-01-02         35.0        7.0  Sunny
2 2017-01-03         28.0        2.0   Snow

In [7]:
# manual input/ using dictionaries
sample_weather_data ={
    'day': ['1/1/2017', '1/2/2017', '1/3/2017'],
    'temperature': [32,35,28],
    'windspeed': [6,7,2],
    'event': ['Rain', 'Sunny', 'Snow']
}
df = pd.DataFrame(sample_weather_data)
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [9]:
# using tuple list
sample_weather_data = {
    ('1/1/2017', 32,6,'Rain'),
    ('1/2/2017', 35,7,'Sunny'),
    ('1/3/2017', 28,2,'Snow')
}

df = pd.DataFrame(data=sample_weather_data,columns=['day', 'temperature', 'windspeed', 'event'])
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [12]:
# using list of dictionaries
# keys(day) - values
sample_weather_data = [
    {'day': '1/1/2017', 'temperature': '32', 'windspeed': '6', 'event': 'Rain'}
]

df = pd.DataFrame(data=sample_weather_data, columns=['day', 'temperature', 'windspeed', 'event'])
df

        day temperature windspeed event
0  1/1/2017          32         6  Rain